// @ts-expect-error — generated by `opennextjs-cloudflare build`, absent until then.
import { default as handler } from "./.open-next/worker.js";

/**
 * Custom Worker entrypoint.
 *
 * OpenNext generates a fetch-only handler. Cron jobs used to be driven by
 * vercel.json hitting two API routes over HTTP; on Workers they arrive as
 * scheduled() invocations instead, so this wrapper re-exports OpenNext's fetch
 * handler unchanged and dispatches cron runs into the very same routes.
 *
 * Dispatching through handler.fetch rather than importing the job functions
 * keeps one code path: the routes keep their own CRON_SECRET check, and
 * hitting them by hand for a manual re-run still behaves identically.
 */

const JOBS: Record<string, string> = {
  "0 8 * * *": "/api/cron/worksnap-sync/",
  "0 9 * * *": "/api/cron/leave-balance-reset/",
};

// Any absolute origin works — the request never leaves the isolate. Using the
// real host keeps logs readable.
const ORIGIN = "https://team.ourworldenergy.com";

export default {
  fetch: handler.fetch,

  async scheduled(
    controller: ScheduledController,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ): Promise<void> {
    const path = JOBS[controller.cron];
    if (!path) {
      console.error(`No job mapped to cron "${controller.cron}"`);
      return;
    }

    const secret = (env as { CRON_SECRET?: string }).CRON_SECRET;
    const request = new Request(new URL(path, ORIGIN), {
      headers: secret ? { authorization: `Bearer ${secret}` } : {},
    });

    const response = await handler.fetch(request, env, ctx);
    const body = await response.text();

    if (!response.ok) {
      // Throwing marks the cron invocation as failed, so it shows up in
      // Workers observability rather than silently logging a 500.
      throw new Error(`${path} failed (${response.status}): ${body.slice(0, 500)}`);
    }
    console.log(`${path} ok: ${body.slice(0, 500)}`);
  },
};
