-- AlterTable
ALTER TABLE "payroll_adjustments"
  ADD COLUMN "cashAdvance" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "hmo" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "tax" DOUBLE PRECISION NOT NULL DEFAULT 0;
